### ISSUE TITLE
cannot read property "func" of undefined

### ISSUE THREAD

**Issue by pawansingewar007** [kevinstumpf/react-native-signature-pad#29]
![screen shot 2017-12-20 at 4 52 26 pm](https://user-images.githubusercontent.com/12911123/34204850-3d729360-e5a6-11e7-83fc-8a8124689f57.png)

Not able to run even this sample code provided in github.

**Comment by jreason** [comment]
@pawansingh123 this is because the PropTypes have is newer versions of ReactNative.
make sure you have the following installed:
https://www.npmjs.com/package/prop-types

open file .\node_modules\react-native-signature-pad\index.js

change this line
import React, { Component } from 'react';
add this line
import PropTypes from 'prop-types';

change the following:

static propTypes = {
    onChange: PropTypes.func,
    onError: PropTypes.func,
    style: View.propTypes.style,
    penColor: PropTypes.string,
    dataURL: PropTypes.string,
  };

**Comment by pawansingewar007** [comment]
@jreason  thanks It worked 👍

**Comment by NelsonPetitos** [comment]
Please I have another issue. I fix this bug like specify by @jreason great by the way. But when I deploy my project with expo, I have this

![img_5124](https://user-images.githubusercontent.com/18627577/36644138-21a630e4-1a56-11e8-8cfa-219392ca15ea.PNG)


 Before I install this lib the app was working very well. Any ideas why ?

**Comment by NelsonPetitos** [comment]
Found the solution. I forgot to change  

style: View.propTypes.style,

-- with the code below --

style: ViewPropTypes.style,

**Comment by disha-nimble** [comment]
> style: ViewPropTypes.style,

i got another issue 
can't find variable: ViewPropTypes

**Comment by NoSaBo** [comment]
> > style: ViewPropTypes.style,
> 
> i got another issue
> can't find variable: ViewPropTypes

just import it from react-native:

import { ViewPropTypes } from "react-native";

**Comment by ReneDH** [comment]
If I install the package with yarn or npm, the version 0.0.8 comes, but the index.js and the package.json are still the old ones. It also does not change if I remove the node-module folder beforehand. Is there a tar.gz - url that I could specify instead of the version number, so that always the right state is loaded?

Thanks

**Comment by timt** [comment]
Version 0.0.9 now published
